#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/ldr.ls -> dist/ldr.js ..."
npx lsc -cp --no-header src/ldr.ls > dist/ldr.js
echo "build src/ldr.styl -> dist/ldr.css ..."
npx stylus -p src/ldr.styl > dist/ldr.css
echo "minifying ldr.js ..."
npx uglifyjs dist/ldr.js > dist/ldr.min.js
echo "minifying ldr.css ..."
npx uglifycss dist/ldr.css > dist/ldr.min.css
echo "deploy dist files to web..."
rm -rf web/static/assets/lib/ldresize/dev
mkdir -p web/static/assets/lib/ldresize/dev
cp dist/* web/static/assets/lib/ldresize/dev
echo "done."
