#!/usr/bin/env bash
mkdir -p dist
echo "build src/ldr.ls -> dist/ldr.js ..."
./node_modules/.bin/lsc -cbp src/ldr.ls > dist/ldr.js
echo "build src/ldr.styl -> dist/ldr.css ..."
./node_modules/.bin/stylus -p src/ldr.styl > dist/ldr.css
echo "minifying ldr.js ..."
./node_modules/.bin/uglifyjs dist/ldr.js > dist/ldr.min.js
echo "minifying ldr.css ..."
./node_modules/.bin/uglifycss dist/ldr.css > dist/ldr.min.css
echo "done."

