// Generated by LiveScript 1.3.1
var ldr, path;
ldr = new ldResize({
  host: svg,
  root: svg
});
path = ld$.find(document, 'path');
ldr.attach([path[6], path[0]]);
ldr.attach([path[2]], true);
setInterval(function(){
  return ldr.attach([path[2]]);
}, 5000);